[workspace]
members = [
    "compiler_tester",
    "solidity_adapter",
    "coverage_watcher",
    "benchmark_analyzer",
    "fuzzer"
]
resolver = "2"

[patch."https://github.com/matter-labs/vm2"]
vm2 = {path = "../vm2"}
