[build]
rustflags = [
    "-W", "missing_docs",
]
incremental = true

[tools.clippy]
warn = [
    "missing_docs_in_private_items",
]

[target.x86_64-apple-darwin]
rustflags = [
    "-W", "missing_docs",
    "-C", "link-arg=-mmacosx-version-min=11.0",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-W", "missing_docs",
    "-C", "link-arg=-mmacosx-version-min=11.0",
]

[profile.release]
strip = true

[env]
BOOST_PREFIX = { value = "/opt/homebrew/lib/", relative = false, force = false }
LLVM_SYS_170_PREFIX = { value = "./target-llvm/target-final/", relative = true, force = false }
SOLC_PREFIX = { value = "./era-solidity/build/", relative = true, force = false }
RUST_BACKTRACE = { value = "0" }
RUST_LOG = { value = "vm=trace" }
