[package]
name = "coverage-watcher"
version = "1.5.0"
authors = [
    "Oleksandr Zarudnyi <a.zarudnyy@matterlabs.dev>",
    "Anton Dyadyuk <a.dyadyuk@matterlabs.dev>",
]
license = "MIT OR Apache-2.0"
edition = "2021"
description = "The integration tests coverage watcher"

[[bin]]
name = "coverage-watcher"
path = "src/coverage_watcher/main.rs"

[dependencies]
structopt = { version = "0.3", default-features = false }
anyhow = "1.0"

serde = { version = "1.0", features = [ "derive" ] }
serde_yaml = "0.9"

era-compiler-common = { git = "https://github.com/matter-labs/era-compiler-common", branch = "main" }
