name: Integration Tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      compiler-tester-ref:
        type: string
        required: true
        description: 'Compiler tester revision to use.'
      llvm-ref:
        type: string
        required: true
        description: 'LLVM revision to use.'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-integration-tests:
    runs-on: ci-runner-compiler
    timeout-minutes: 720
    container:
      image: matterlabs/llvm_runner:ubuntu22-llvm17-latest
      options: -m 110g
    steps:

      - name: Checkout compiler-tester
        uses: actions/checkout@v4
        with:
          repository: matter-labs/era-compiler-tester
          ref: ${{ inputs.compiler-tester-ref || '' }}
          submodules: recursive

      - name: Checkout LLVM
        if: inputs.llvm-ref != ''
        uses: actions/checkout@v4
        with:
          repository: matter-labs/era-compiler-llvm
          ref: ${{ inputs.llvm-ref }}
          path: llvm

      - name: Build LLVM
        uses: ./.github/actions/build-llvm
        with:
          extra-args: "\\-DLLVM_ENABLE_WERROR=On \\-DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
          enable-tests: true
          enable-assertions: true
          clone-llvm: ${{ inputs.llvm-ref == '' && 'true' || 'false' }}

      - name: Build compiler-tester
        run: cargo build --verbose --release --bin 'compiler-tester'

      - name: Build compilers
        env:
          CARGO_CHECKOUT_DIR: /usr/local/cargo/git/checkouts
        run: |
          cargo build --verbose --release \
            --manifest-path ${CARGO_CHECKOUT_DIR}/era-compiler-solidity-*/*/Cargo.toml \
            --target-dir './target-zksolc/'
          cargo build --verbose --release \
            --manifest-path ${CARGO_CHECKOUT_DIR}/era-compiler-vyper-*/*/Cargo.toml \
            --target-dir './target-zkvyper/'

      - name: Run integration tests
        run: |
          ./target/release/compiler-tester \
            --zksolc './target-zksolc/release/zksolc' \
            --zkvyper './target-zkvyper/release/zkvyper'

      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        if: ${{ failure() || success() }} # Skip canceled jobs
        with:
          status: ${{ job.status }}
          fields: repo,commit,author,action,eventName,ref,workflow,job,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
