name: Leaked Secrets Scan

on:
  pull_request:
  workflow_call:

jobs:

  secrets-scan:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.75.1
        with:
          base: ${{ github.event.repository.default_branch }}
          extra_args: --debug --only-verified
